#!/usr/bin/env node

var fs = require('fs');
var conf = require('./erlang_conf');
var $ = require('shelljs');

var filename = './data.conf'
var data = fs.readFileSync(filename, {'encoding': 'utf8'});

$.echo('================');
$.echo(data);
$.echo('================');
var data2 = conf.parse(data);
$.echo(data2);
